// Auto-generated by scripts/setup-supabase.mjs — do not commit secrets beyond anon key
window.PRD_FORGE_SUPABASE = {
  url: 'https://vxcxaiylcjrcukgyfath.supabase.co',
  anonKey: 'sb_publishable_SgHglWa2ERsRM7jyKb5OpA_OLrYUxqw'
};
